# Generated by Django 3.2.2 on 2021-05-09 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teleBot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_subscription_data',
            name='pincode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_subscription_data', to='teleBot.pincode'),
        ),
    ]
