# Generated by Django 3.2.2 on 2021-05-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleBot', '0002_alter_user_subscription_data_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='teligram_user',
            name='can_add',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='user_subscription_data',
            unique_together={('user', 'pincode')},
        ),
        migrations.RemoveField(
            model_name='user_subscription_data',
            name='can_modify',
        ),
    ]
