# Generated by Django 3.2.2 on 2021-05-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleBot', '0003_auto_20210511_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='teligram_user',
            name='can_delete',
            field=models.BooleanField(default=False),
        ),
    ]
