# Generated by Django 3.2.2 on 2021-05-11 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleBot', '0005_auto_20210511_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teligram_user',
            name='deregister',
            field=models.BooleanField(default=False),
        ),
    ]
